log_level: debug
server_env: local-dev
log_filename: /data/logs/open-account.log
# listen 0.0.0.0 only for test.
listen: 0.0.0.0:2021
check_sign: true
debug: true
disable_stacktrace: false
super_key_for_test: 91af98b3bd246347f8d6eea0573ef7e7
super_code_for_test: 0bce718389e18ba44fa98b9da51fc3e3
account_database:
  dialect: mysql
  host: 127.0.0.1
  port: 3306
  db_name: openaccount
  user: openaccount
  password: 123456
  debug: true
token_redis:
  cache_name: token
  addr: 127.0.0.1:6379
  db_index: 1
sms_redis:
  cache_name: sms
  addr: 127.0.0.1:6379
  db_index: 2
